const LOGIN = 'LOGIN'
const SIGN_UP = 'SIGN_UP'
const LOG_OUT = 'LOG_OUT'
const SET_TOKENS = 'SET_TOKENS'
const SET_USER_WITH_TOKENS = 'SET_USER_WITH_TOKENS'
const SET_LOADING = 'SET_LOADING'

const AUTH_ACTIONS = {
  LOGIN,
  SIGN_UP,
  LOG_OUT,
  SET_TOKENS,
  SET_USER_WITH_TOKENS,
  SET_LOADING
}
export default AUTH_ACTIONS
