const MENU_OPTIONS_SORT_BY_FIELD = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE'
}

const MENU_OPTIONS_SORT_TYPE = {
  ASC: 'ASC',
  DESC: 'DESC'
}

export { MENU_OPTIONS_SORT_BY_FIELD, MENU_OPTIONS_SORT_TYPE }
