export const CREATE_TASK = 'CREATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const CHANGE_DONE = 'CHANGE_DONE'
export const CHANGE_FILTER = 'CHANGE_FILTER'
