const PREFIX = 'img-crop'

const ZOOM_INITIAL = 1
const ZOOM_STEP = 0.1
const ROTATION_INITIAL = 0
const ROTATION_MIN = -180
const ROTATION_MAX = 180
const ROTATION_STEP = 1

const ASPECT_MIN = 0.5
const ASPECT_MAX = 2
const ASPECT_STEP = 0.01

export {
  PREFIX,
  ZOOM_INITIAL,
  ZOOM_STEP,
  ROTATION_INITIAL,
  ROTATION_MIN,
  ROTATION_MAX,
  ROTATION_STEP,
  ASPECT_MIN,
  ASPECT_MAX,
  ASPECT_STEP
}
